export const CATEGORIES = [
  "Culture",
  "Comics",
  "International",
  "Crypto",
  "History",
  "Humor",
  "Education",
  "Business",
  "Finance",
  "Food & Drink",
  "Sports",
  "Art & Illustration",
  "World Politics",
  "Health Politics",
  "Fashion & Beauty",
  "Music",
  "Faith & Spirituality",
  "News",
  "Climate & Environment",
  "Science",
  "Literature",
  "Fiction",
  "Health & Wellness",
  "Design",
  "Travel",
  "Parenting",
  "Philosophy",
  "Technology",
];
